version: "3.8"

services:
  postgres-etl:
    image: postgres
    container_name: postgres-etl
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    volumes:
      - etl_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - postgresql
    restart: unless-stopped

  pgadmin-etl:
    container_name: pgadmin-etl
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - 5050:80
    networks:
      - postgresql
    restart: unless-stopped

networks:
  postgresql:
    driver: bridge

volumes:
  etl_data:
  pgadmin:
